// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package database

import (
	"context"
	"database/sql"
)

const createApplications = `-- name: CreateApplications :one
INSERT INTO applications( department, status, companyid, positionid, interviewId, userid)
VALUES($1, $2, $3,$4, $5, $6)
RETURNING id, department, status, companyid, positionid, interviewid, userid, date_applied
`

type CreateApplicationsParams struct {
	Department  string
	Status      string
	Companyid   int32
	Positionid  int32
	Interviewid sql.NullInt32
	Userid      int32
}

func (q *Queries) CreateApplications(ctx context.Context, arg CreateApplicationsParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplications,
		arg.Department,
		arg.Status,
		arg.Companyid,
		arg.Positionid,
		arg.Interviewid,
		arg.Userid,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Department,
		&i.Status,
		&i.Companyid,
		&i.Positionid,
		&i.Interviewid,
		&i.Userid,
		&i.DateApplied,
	)
	return i, err
}
