// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Company.sql

package database

import (
	"context"
	"database/sql"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies( companyName, companyLocation, companyWebsite, companyEmail, HiringManagerName)
VALUES($1, $2, $3, $4, $5)
RETURNING companyid, companyname, companylocation, companywebsite, companyemail, hiringmanagername
`

type CreateCompanyParams struct {
	Companyname       string
	Companylocation   string
	Companywebsite    string
	Companyemail      string
	Hiringmanagername sql.NullString
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany,
		arg.Companyname,
		arg.Companylocation,
		arg.Companywebsite,
		arg.Companyemail,
		arg.Hiringmanagername,
	)
	var i Company
	err := row.Scan(
		&i.Companyid,
		&i.Companyname,
		&i.Companylocation,
		&i.Companywebsite,
		&i.Companyemail,
		&i.Hiringmanagername,
	)
	return i, err
}
