// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Account struct {
	ID     int32
	Name   string
	Email  string
	Role   string
	Apikey string
}

type Application struct {
	ID          int32
	Department  string
	Status      string
	Company     int32
	Position    int32
	Interviewid sql.NullInt32
}

type Company struct {
	Companyid         int32
	Companyname       string
	Companylocation   string
	Companywebsite    string
	Companyemail      string
	Hiringmanagername sql.NullString
}

type Interview struct {
	ID            int32
	Status        string
	Interviewdate time.Time
}

type Job struct {
	Postionid            int32
	Positionname         string
	Companyid            int32
	Experiencerequired   string
	Expectedcompensation string
	Employmenttype       string
	Joblocationtype      string
}
